cargo-features = ["per-package-target"]

[package]
name = "elpytios-sys"
version = "0.1.0"
edition = "2024"
rust-version = "1.98"

forced-target = "./target-specs/x86_64-unknown-elpytios.json"

[dependencies]
alloc = { path = "rust-src/alloc" }
core = { path = "rust-src/core" }
compiler_builtins = { path = "rust-src/compiler-builtins/compiler-builtins" }
