[unstable]
codegen-backend = true
json-target-spec = true

[build]
rustc-wrapper = "./rustc-sysroot"
target = "target-specs/x86_64-unknown-elpytios.json"

[profile.bootloader]
inherits = "release"
lto = "thin"

[profile.bootloader_debug]
inherits = "bootloader"
opt-level = 0
debug-assertions = true
debug = "full"

[target.x86_64-unknown-none]
rustflags = [
    "-C",
    "code-model=kernel",
    "-C",
    "relocation-model=pie",
    "-C",
    "linker-flavor=ld.lld",
]
